# Site settings
title: ButtFly Blog
email: 315585758@qq.com
description: "!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  ButtFly
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
